export const GET_CUSTOMER_ADDRESS = "GET_CUSTOMER_ADDRESS";
export const GET_CUSTOMER_LIST = "GET_CUSTOMER_LIST";
export const CUSTOMER_ADDRESS_LOADED = "CUSTOMER_ADDRESS_LOADED";
export const CUSTOMER_LIST_LOADED = "CUSTOMER_LIST_LOADED";
export const CUSTOMER_ADDRESS_LOAD_ERROR="CUSTOMER_ADDRESS_LOAD_ERROR";
export const CUSTOMER_LIST_LOAD_ERROR="CUSTOMER_LIST_LOAD_ERROR";
export const CUSTOMER_INVALID_ID=-1;
export const CUSTOMER_INVALID_ID_ERROR="CUSTOMER_INVALID_ID_ERROR";